micropost/config/routes.rb
Micropost::Application.routes.draw do
  devise_for :users

  resources :posts
  resources :users

  root :to => 'posts#index'

end

micropost/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :user_id

  belongs_to :user

  validates :content, presence: true,
                      length: { minimum: 6 }
  validates :user_id, presence: true
end

micropost/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :description, :email, :location, :name

  has_many :posts

  validates :email, presence: true,
                    uniqueness: true
  validates :password, presence: true
  validates :name, presence: true
end

micropost/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

micropost/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :get_users
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('created_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = current_user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
  def get_users
    @users = User.all.map {|user| [user.name, user.id]}
  end
end

micropost/app/helpers/application_helper.rb
module ApplicationHelper
  def flass_class(type)
    case type
      when :success then "success"
      when :error   then "warning"
      when :alert   then "warning"
      when :notice  then ""
      else "info"
    end
  end
end

micropost/app/helpers/posts_helper.rb
module PostsHelper
end

micropost/app/helpers/users_helper.rb
module UsersHelper
end

micropost/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Micropost" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to 'Micropost', root_path %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="divider"></li>
          <li>
            <%= link_to 'Posts', posts_path %>
          </li>
        </ul>

        <!-- Right Nav Section -->
        <ul class="right">
          <li class="divider"></li>
          <% if user_signed_in? %>
          <li>
            <%= link_to current_user.name, edit_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
          </li>
          <% else %>
          <li class="active">
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
          <% end %>
        </ul>


      </section>
    </nav>
    <div class="row">
      <div class="columns large-12">
        <br>
        <% flash.each do |type, message| %>
        <div data-alert class="alert-box radius <%= flass_class type %>">
          <%= message %>
          <a href="#" class="close">&times;</a>
        </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

micropost/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit nil, class: 'button' %>
  </div>
<% end %>

micropost/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post, class: 'button' %>

micropost/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<%= link_to 'New Post', new_post_path, class: 'button' %>

<% @posts.each do |post| %>
  <hr>
  <div class="row">
    <div class="columns large-9 medium-6">
      <blockquote>
        <%= post.content %>
        <cite><%= post.user.name %> - <em><%= time_ago_in_words(post.created_at) %> ago</em></cite>
      </blockquote>
    </div>
    <div class="columns large-3 medium-6">
      <ul class="inline-list">
        <li><%= link_to 'Show', post %></li>
        <li>
        <%= link_to 'Edit', edit_post_path(post) %>
        </li>
        <li><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
  </div>
<% end %>

micropost/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

micropost/app/views/posts/show.html.erb
<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>User:</b>
  <%= @post.user.name %>
</p>


<%= link_to 'Edit', edit_post_path(@post), class: 'button' %>